# Generated by Django 5.2.2 on 2025-06-06 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_fee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fee',
            old_name='payment_date',
            new_name='due_date',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='fee',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='fee',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='fee',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
    ]
