# Generated by Django 5.2.2 on 2025-06-08 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_rename_payment_date_fee_due_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='due_date',
            field=models.DateField(),
        ),
    ]
